name: Release (SLSA3)

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write   # REQUIRED for SLSA + PyPI trusted publishing

jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-22.04

    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build sdist and wheel
        run: python -m build

      - name: Generate hashes
        id: hash
        run: |
          echo "hashes=$(sha256sum dist/* | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/*

  provenance:
    name: Generate SLSA provenance
    needs: build
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator-generic-ossf-slsa3-publish.yml@v2.0.0
    with:
      base64-subjects: ${{ needs.build.outputs.hashes }}
